repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-ast
-   repo: local
    hooks:
    -   id: black
        name: Black
        description: This hook runs black within our project's environment.
        entry: poetry run black .
        language: system
        types: [python]
